# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da6203a1d9b9826634a677616b8e9c227284c30ccdb96b63da3525e0069df26e819cb3f8e5aac0f0094900a4f71d56db23b7782378bf6cff88eb7d370b8e4b82

test:
  secret_key_base: f7cace36355de39925510e756e7abcd81209a387b1eb142adbe266bd313c61d2ac06da81b2648877bc50a951eb05a751151fecb48142f09ad984b948ccbe9129

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
